apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: <your-dockerhub-username>/messaging-app:2.0  # Updated version to 2.0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: messaging-app-db
        - name: DATABASE_PORT
          value: "3306"
