name: Django CI

on:
  push:
    branches:
      - main  # Trigger the workflow for pushes to the main branch (adjust as needed)
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting the main branch (adjust as needed)

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    services:
      mysql:
        image: mysql:5.7  # Use MySQL 5.7 for database service
        env:
          MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MySQL
          MYSQL_DATABASE: test_db  # Name of the database for testing
        ports:
          - 3306:3306  # Expose MySQL on port 3306
        options: >-
          --health-cmd="mysqladmin --user=root --password=rootpassword ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can change the version if needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install flake8 coverage pytest pytest-cov     # Install code quality and coverage tools

      # Run Flake8 linting
      - name: Run Flake8 linting
        run: |
          source venv/bin/activate
          flake8 messaging_app/ --max-line-length=79
        # Fail the build if linting errors are detected
        continue-on-error: false

      # Set up the MySQL database connection (required for Django to run tests)
      - name: Set up MySQL database
        run: |
          source venv/bin/activate
          python messaging_app/manage.py migrate  # Apply migrations

      # Run tests and collect coverage
      - name: Run Django tests with coverage
       run: |
         source venv/bin/activate
         pytest --cov=messaging_app --cov-report=xml --cov-report=term messaging_app/tests

      # Upload coverage report
      - name: Upload coverage report
       uses: actions/upload-artifact@v3
       with:
         name: coverage-report
         path: coverage.xml